In [1]:
from GeneralisedWick import *

In [2]:
fockTensor = Tensor("f", ['g'], ['g'])
h1Tensor = Tensor("h", ['g'], ['g'])
h2Tensor = Tensor("v", ['g', 'g'], ['g', 'g'])
t2Tensor = Tensor("{t_{2}}", ['p', 'p'], ['h', 'h'])

In [3]:
fockTensor.getAllDiagramsGeneral()

('h',) ('h',)
['h']
['h']
['h']
['h']
('h',) ('p',)
['h']
['p']
['h']
['p']
('p',) ('h',)
['p']
['h']
['p']
['h']
('p',) ('p',)
['p']
['p']
['p']
['p']


In [4]:
h2Tensor.getAllDiagramsGeneral()

('h', 'h') ('h', 'h')
['h', 'h']
['h', 'h']
['h', 'h']
['h', 'h']
('h', 'h') ('h', 'p')
['h', 'h']
['h', 'p']
['h', 'h']
['h', 'p']
('h', 'h') ('p', 'h')
['h', 'h']
['p', 'h']
['h', 'h']
['p', 'h']
('h', 'h') ('p', 'p')
['h', 'h']
['p', 'p']
['h', 'h']
['p', 'p']
('h', 'p') ('h', 'h')
['h', 'p']
['h', 'h']
['h', 'p']
['h', 'h']
('h', 'p') ('h', 'p')
['h', 'p']
['h', 'p']
['h', 'p']
['h', 'p']
('h', 'p') ('p', 'h')
['h', 'p']
['p', 'h']
['h', 'p']
['p', 'h']
('h', 'p') ('p', 'p')
['h', 'p']
['p', 'p']
['h', 'p']
['p', 'p']
('p', 'h') ('h', 'h')
['p', 'h']
['h', 'h']
['p', 'h']
['h', 'h']
('p', 'h') ('h', 'p')
['p', 'h']
['h', 'p']
['p', 'h']
['h', 'p']
('p', 'h') ('p', 'h')
['p', 'h']
['p', 'h']
['p', 'h']
['p', 'h']
('p', 'h') ('p', 'p')
['p', 'h']
['p', 'p']
['p', 'h']
['p', 'p']
('p', 'p') ('h', 'h')
['p', 'p']
['h', 'h']
['p', 'p']
['h', 'h']
('p', 'p') ('h', 'p')
['p', 'p']
['h', 'p']
['p', 'p']
['h', 'p']
('p', 'p') ('p', 'h')
['p', 'p']
['p', 'h']
['p', 'p']
['p', 'h']
('p', 'p')

In [5]:
print(*h2Tensor.diagrams)

v_{hh}^{hh} v_{hh}^{hp} v_{hh}^{ph} v_{hh}^{pp} v_{hp}^{hh} v_{hp}^{hp} v_{hp}^{ph} v_{hp}^{pp} v_{ph}^{hh} v_{ph}^{hp} v_{ph}^{ph} v_{ph}^{pp} v_{pp}^{hh} v_{pp}^{hp} v_{pp}^{ph} v_{pp}^{pp}


In [6]:
def commutator(operator1, operator2):
    return operator1 * operator2 + (-1) * operator2 * operator1

In [7]:
def BCHSimilarityTransform(H, T, order):
    result = H
    for k in range(order):
        nestedCommutator = H
        for i in range(k + 1):
            nestedCommutator = commutator(nestedCommutator, T)
        result += (1 / factorial(k + 1)) * nestedCommutator
    return result

In [8]:
def projectionManifold(excitationLevel):
    return Tensor('\Phi', ['h'] * excitationLevel, ['p'] * excitationLevel)

In [9]:
normalOrderedHamiltonian = sum(fockTensor.diagrams) + (1. / 2.) * sum(h2Tensor.diagrams)

In [10]:
print(normalOrderedHamiltonian)

1.0 * f_{h_{0}}^{h_{1}}
 + 1.0 * f_{h_{0}}^{p_{0}}
 + 1.0 * f_{p_{0}}^{h_{0}}
 + 1.0 * f_{p_{0}}^{p_{1}}
 + 0.5 * v_{h_{0}h_{1}}^{h_{2}h_{3}}
 + 0.5 * v_{h_{0}h_{1}}^{h_{2}p_{0}}
 + 0.5 * v_{h_{0}h_{1}}^{p_{0}h_{2}}
 + 0.5 * v_{h_{0}h_{1}}^{p_{0}p_{1}}
 + 0.5 * v_{h_{0}p_{0}}^{h_{1}h_{2}}
 + 0.5 * v_{h_{0}p_{0}}^{h_{1}p_{1}}
 + 0.5 * v_{h_{0}p_{0}}^{p_{1}h_{1}}
 + 0.5 * v_{h_{0}p_{0}}^{p_{1}p_{2}}
 + 0.5 * v_{p_{0}h_{0}}^{h_{1}h_{2}}
 + 0.5 * v_{p_{0}h_{0}}^{h_{1}p_{1}}
 + 0.5 * v_{p_{0}h_{0}}^{p_{1}h_{1}}
 + 0.5 * v_{p_{0}h_{0}}^{p_{1}p_{2}}
 + 0.5 * v_{p_{0}p_{1}}^{h_{0}h_{1}}
 + 0.5 * v_{p_{0}p_{1}}^{h_{0}p_{2}}
 + 0.5 * v_{p_{0}p_{1}}^{p_{2}h_{0}}
 + 0.5 * v_{p_{0}p_{1}}^{p_{2}p_{3}}


In [11]:
BCHTransformedNormalOrderedHamiltonian = BCHSimilarityTransform(normalOrderedHamiltonian, 0.25 * t2Tensor, 4)

In [12]:
print(BCHTransformedNormalOrderedHamiltonian)

1.0 * f_{h_{0}}^{h_{1}}
 + 1.0 * f_{h_{0}}^{p_{0}}
 + 1.0 * f_{p_{0}}^{h_{0}}
 + 1.0 * f_{p_{0}}^{p_{1}}
 + 0.5 * v_{h_{0}h_{1}}^{h_{2}h_{3}}
 + 0.5 * v_{h_{0}h_{1}}^{h_{2}p_{0}}
 + 0.5 * v_{h_{0}h_{1}}^{p_{0}h_{2}}
 + 0.5 * v_{h_{0}h_{1}}^{p_{0}p_{1}}
 + 0.5 * v_{h_{0}p_{0}}^{h_{1}h_{2}}
 + 0.5 * v_{h_{0}p_{0}}^{h_{1}p_{1}}
 + 0.5 * v_{h_{0}p_{0}}^{p_{1}h_{1}}
 + 0.5 * v_{h_{0}p_{0}}^{p_{1}p_{2}}
 + 0.5 * v_{p_{0}h_{0}}^{h_{1}h_{2}}
 + 0.5 * v_{p_{0}h_{0}}^{h_{1}p_{1}}
 + 0.5 * v_{p_{0}h_{0}}^{p_{1}h_{1}}
 + 0.5 * v_{p_{0}h_{0}}^{p_{1}p_{2}}
 + 0.5 * v_{p_{0}p_{1}}^{h_{0}h_{1}}
 + 0.5 * v_{p_{0}p_{1}}^{h_{0}p_{2}}
 + 0.5 * v_{p_{0}p_{1}}^{p_{2}h_{0}}
 + 0.5 * v_{p_{0}p_{1}}^{p_{2}p_{3}}
 + 0.25 * f_{h_{0}}^{h_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{2}h_{3}}
 + 0.25 * f_{h_{0}}^{p_{0}}{t_{2}}_{p_{1}p_{2}}^{h_{1}h_{2}}
 + 0.25 * f_{p_{0}}^{h_{0}}{t_{2}}_{p_{1}p_{2}}^{h_{1}h_{2}}
 + 0.25 * f_{p_{0}}^{p_{1}}{t_{2}}_{p_{2}p_{3}}^{h_{0}h_{1}}
 + 0.125 * v_{h_{0}h_{1}}^{h_{2}h_{3}}{t_{2}}_{p_{0}p_{1}}^

In [13]:
EnergyTerms = [evaluateWick(BCHSimilarityTransform(fD, (1./4.) * t2Tensor, 4), spinFree=True) for fD in fockTensor.diagrams] + [evaluateWick(BCHSimilarityTransform(0.5 * vD, (1./4.) * t2Tensor, 4), spinFree=True) for vD in h2Tensor.diagrams]

KeyboardInterrupt: 

In [ ]:
print(*EnergyTerms)

       0.5 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{1}p_{0}}^{h_{1}h_{0}}
 + -0.25 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{1}h_{0}}
 + -0.25 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{1}p_{0}}^{h_{0}h_{1}}
 + 0.5 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{0}h_{1}}            


In [ ]:
recursivePartialContraction(BCHTransformedNormalOrderedHamiltonian.summandList[-1].getOperator(spinFree=True).summandList[0], 10)

20 10
case 0


In [ ]:
oP = BCHTransformedNormalOrderedHamiltonian.summandList[-1].getOperator(spinFree=True).summandList[0]

In [ ]:
print(oP)

1.0 * a^{p_{0}\beta}a^{p_{1}\beta}a_{h_{1}\beta}a_{h_{0}\beta}a^{p_{2}\beta}a^{p_{3}\beta}a_{h_{3}\beta}a_{h_{2}\beta}a^{p_{4}\beta}a^{p_{5}\beta}a_{h_{5}\beta}a_{h_{4}\beta}a^{p_{6}\beta}a^{p_{7}\beta}a_{h_{7}\beta}a_{h_{6}\beta}a^{p_{8}\beta}a^{p_{9}\beta}a_{p_{11}\beta}a_{p_{10}\beta}


In [ ]:
recursiveFullContraction(oP)

0

In [ ]:
def recursivePartialContraction(operatorProduct_, nFreeIndexPairs=0, speedup=False):
    operatorList_ = operatorProduct_.operatorList
    print(len(operatorList_), nFreeIndexPairs)
    if speedup:
        if not sum(o.quasi_cre_ann for o in operatorList_) == sum(not o.quasi_cre_ann for o in operatorList_):
            return 0
    existingContractions = operatorProduct_.contractionsList
    if len(operatorList_) == 2 * nFreeIndexPairs:
        print("case 0")
        return operatorProduct_
#    elif len(operatorList_) == 2 * nFreeIndexPairs + 2:
#        if canContract(operatorList_[0], operatorList_[1]):
#            contractionTuple = tuple()
#            if operatorList_[0].creation_annihilation:
#                contractionTuple = (operatorList_[0].index, operatorList_[1].index)
#            else:
#                contractionTuple = (operatorList_[1].index, operatorList_[0].index)
#            print("case 10")
#            return operatorProduct([], operatorProduct_.prefactor, existingContractions + [contractionTuple])
#        else:
#            print("case 11")
#            return 0
    elif len(operatorList_) % 2 == 0:
        result = 0
        for i in range(1, len(operatorList_) - 1):
            if canContract(operatorList_[0], operatorList_[i]):
                contractionTuple = tuple()
                if operatorList_[0].creation_annihilation:
                    contractionTuple = (operatorList_[0].index, operatorList_[i].index)
                else:
                    contractionTuple = (operatorList_[i].index, operatorList_[0].index)
                print("case 2")
                result += pow(-1, i-1) * recursivePartialContraction(operatorProduct(operatorList_[1:i] + operatorList_[i+1:], operatorProduct_.prefactor, existingContractions + [contractionTuple]), nFreeIndexPairs)
        if canContract(operatorList_[0], operatorList_[-1]):
            contractionTuple = tuple()
            if operatorList_[0].creation_annihilation:
                contractionTuple = (operatorList_[0].index, operatorList_[-1].index)
            else:
                contractionTuple = (operatorList_[-1].index, operatorList_[0].index)
            print("case 3")
            result += recursivePartialContraction(operatorProduct(operatorList_[1:-1], operatorProduct_.prefactor, existingContractions + [contractionTuple]), nFreeIndexPairs)
        return result
    else:
        print("case 4")
        return 0

In [ ]:
print(recursivePartialContraction(oP, 10))

20 10
case 0
1.0 * a^{p_{0}\beta}a^{p_{1}\beta}a_{h_{1}\beta}a_{h_{0}\beta}a^{p_{2}\beta}a^{p_{3}\beta}a_{h_{3}\beta}a_{h_{2}\beta}a^{p_{4}\beta}a^{p_{5}\beta}a_{h_{5}\beta}a_{h_{4}\beta}a^{p_{6}\beta}a^{p_{7}\beta}a_{h_{7}\beta}a_{h_{6}\beta}a^{p_{8}\beta}a^{p_{9}\beta}a_{p_{11}\beta}a_{p_{10}\beta}


In [ ]:
testTensorProduct = h2Tensor.diagrams[3] * t2Tensor

In [ ]:
print(testTensorProduct.getOperator(spinFree=True).summandList[0])
print(recursivePartialContraction(testTensorProduct.getOperator(spinFree=True).summandList[0], 3))

1.0 * a^{h_{0}\beta}a^{h_{1}\beta}a_{p_{1}\beta}a_{p_{0}\beta}a^{p_{2}\beta}a^{p_{3}\beta}a_{h_{3}\beta}a_{h_{2}\beta}
8 3
case 2
6 3
case 0
case 3
6 3
case 0
-1.0 * a^{h_{1}\beta}a_{p_{1}\beta}a_{p_{0}\beta}a^{p_{2}\beta}a^{p_{3}\beta}a_{h_{2}\beta}\delta^{h_{0}}_{h_{3}}
 + 1.0 * a^{h_{1}\beta}a_{p_{1}\beta}a_{p_{0}\beta}a^{p_{2}\beta}a^{p_{3}\beta}a_{h_{3}\beta}\delta^{h_{0}}_{h_{2}}


In [ ]:
#h2Tensor.assignDiagramArrays()

In [ ]:
from itertools import combinations

In [ ]:
def anticommuteInPlace(operatorProduct_, first):
    '''
    Apply fermionic anticommutation relation in place to two adjacent second-quantized operators in an operatorProduct
    '''
    operatorList_ = operatorProduct_.operatorList
    if operatorList_ == []:
        return
    firstOperatorCopy = deepcopy(operatorList_[first])
    operatorList_[first], operatorList_[first + 1] = operatorList_[first + 1], firstOperatorCopy
    operatorProduct_.prefactor = -operatorProduct_.prefactor
    return

def contract(operatorProduct_, first, second):
    '''
    Make a contraction between the indices of operators at the positions given by first and second in operatorProduct_
    '''
    operatorList_ = operatorProduct_.operatorList
    existingContractions = operatorProduct_.contractionsList
    #Case that operatorProduct_ is a scalar
    if operatorList_ == []:
        return operatorProduct_
    if canContract(operatorList_[first], operatorList_[second]):
        contractionTuple = tuple()
        if operatorList_[0].creation_annihilation:
            contractionTuple = (operatorList_[first].index, operatorList_[second].index)
        else:
            contractionTuple = (operatorList_[second].index, operatorList_[first].index)
        return operatorProduct(operatorList_[2:], operatorProduct_.prefactor, existingContractions + [contractionTuple])
#    firstIndex = operatorList_[first].orbital
#    secondIndex = operatorList_[second].orbital
#    if firstIndex == secondIndex and operatorList_[first].spin == operatorList_[second].spin:
#        if not bool(operatorList_[first].quasi_cre_ann) and bool(operatorList_[second].quasi_cre_ann):
#            return operatorProduct(operatorList_[:first] + operatorList_[first+1:second] + operatorList_[second + 1:], operatorProduct_.prefactor * ((-1) ** (1 + second - first)))
    return operatorProduct([],0)

def reorderForContraction(operatorProduct_, first, second):
    '''
    Reorder operators using anticommutation relation so that two operators to be contracted are in positions 0 and 1
    '''
    operatorProductCopy = deepcopy(operatorProduct_)
    i = first
    j = second
    while i > 0:
        anticommuteInPlace(operatorProductCopy, i-1)
        i = i - 1
    while j > 1:
        anticommuteInPlace(operatorProductCopy, j-1)
        j = j - 1
    return operatorProductCopy

def reorderForMultipleContraction(operatorProduct_, pairsList):
    '''
    Reorder operators using anticommutation relation so that each pair of operators to be contracted are adjacent
    '''
    operatorProductCopy = deepcopy(operatorProduct_)
    finalPosition = 0
    for positionPair in pairsList:
        i = positionPair[0]
        j = positionPair[1]
        while i > finalPosition:
            anticommuteInPlace(operatorProductCopy, i-1)
            i = i - 1
        while j > finalPosition + 1:
            anticommuteInPlace(operatorProductCopy, j-1)
            j = j - 1
        finalPosition = finalPosition + 2
    return operatorProductCopy

def updateFlattenedPositionList(flattenedPositions):
    for i in range(len(flattenedPositions)):
        if flattenedPositions[i] > flattenedPositions[1]:
            flattenedPositions[i] -= 2
        elif flattenedPositions[i] > flattenedPositions[0]:
            flattenedPositions[i] -= 1
    return flattenedPositions[2:]

def multipleContraction(operatorProduct_, positionPairsList):
    '''
    Contractions between multiple pairs of operators in a product, at the positions given by entries 2i and 2i+1 in positionPairsList
    '''
    product = copy(operatorProduct_)
    while len(positionPairsList) > 0:
#    for positionPair in pairsList:
        reorderedProduct = reorderForContraction(product, positionPairsList[0], positionPairsList[1])
        product = contract(reorderedProduct, 0, 1)
        positionPairsList = updateFlattenedPositionList(positionPairsList) #NOTE: reduces length of positionPairsList by 2
    return product

def genPairOrderedLists(list_):
    '''
    Given an ordered list with an even number of elements, returns list of all permutations of that list where each adjacent pair is ordered, and where the first elements of pairs are ordered
    !!!WOULD BE BETTER AS GENERATOR!!!
    '''
    pairOrderedLists = []
    if len(list_) == 2:
        pairOrderedLists.append(list_)
    else:
        for i in range(1,len(list_)):
            swappedList = [list_[0]] + [list_[i]] + list_[1:i]
            if i < len(list_):
                swappedList = swappedList + list_[i+1:]
            subLists = genPairOrderedLists(swappedList[2:])
            for l in range(len(subLists)):
                pairOrderedLists.append(swappedList[:2] + subLists[l])
    return pairOrderedLists

def getPositionsForMultipleContraction(operatorProduct_, n):
    nOperators = len(operatorProduct_.operatorList)
    operatorPositions = range(nOperators)
    nToChoose = 2 * n
    if nToChoose <= nOperators:
        return combinations(operatorPositions, nToChoose)

def sumNFoldContractions(operatorProduct_, n):
    if isinstance(operatorProduct_, operatorSum):
        return sum([sumNFoldContractions(summand, n) for summand in operatorProduct_.summandList])
    chosenPositions = getPositionsForMultipleContraction(operatorProduct_, n)
    if n == 0:
        return operatorSum([operatorProduct_])
    operatorSum_ = operatorSum([])
    for c in chosenPositions:
#        pairOrderedList = genPairOrderedLists(list(c))
        pairOrderedList = pairOrderedListsGenerator(list(c))
        for l in pairOrderedList:
            term = multipleContraction(operatorProduct_, l)
#            print(term)
            operatorSum_ = operatorSum_ + term
    return operatorSum_

def wickExpand(operator, vacuum):
    if isinstance(operator, operatorSum):
        wickExpansion = operatorSum([])
        for product in operator.summandList:
            wickExpansion = wickExpansion + wickExpand(product, vacuum)
        return wickExpansion
    operator.checkNilpotency()
    wickExpansion = operatorSum([normalOrder(operator, vacuum)])
    highestOrder = len(operator.operatorList) // 2
    for n in range(highestOrder):
        wickExpansion = wickExpansion + sumNFoldContractions(operator, n + 1)
    return normalOrder(wickExpansion, vacuum)

In [ ]:
print(testTensorProduct.getOperator(spinFree=True).summandList[0])
print(sumNFoldContractions(testTensorProduct.getOperator(spinFree=True).summandList[0], 1))

1.0 * a^{h_{0}\beta}a^{h_{1}\beta}a_{p_{1}\beta}a_{p_{0}\beta}a^{p_{2}\beta}a^{p_{3}\beta}a_{h_{3}\beta}a_{h_{2}\beta}
-1.0 * a^{h_{1}\beta}a_{p_{1}\beta}a_{p_{0}\beta}a^{p_{2}\beta}a^{p_{3}\beta}a_{h_{2}\beta}\delta^{h_{0}}_{h_{3}}
 + 1.0 * a^{h_{1}\beta}a_{p_{1}\beta}a_{p_{0}\beta}a^{p_{2}\beta}a^{p_{3}\beta}a_{h_{3}\beta}\delta^{h_{0}}_{h_{2}}
 + 1.0 * a^{h_{0}\beta}a_{p_{1}\beta}a_{p_{0}\beta}a^{p_{2}\beta}a^{p_{3}\beta}a_{h_{2}\beta}\delta^{h_{1}}_{h_{3}}
 + -1.0 * a^{h_{0}\beta}a_{p_{1}\beta}a_{p_{0}\beta}a^{p_{2}\beta}a^{p_{3}\beta}a_{h_{3}\beta}\delta^{h_{1}}_{h_{2}}
 + -1.0 * a^{h_{0}\beta}a^{h_{1}\beta}a_{p_{0}\beta}a^{p_{3}\beta}a_{h_{3}\beta}a_{h_{2}\beta}\delta^{p_{2}}_{p_{1}}
 + 1.0 * a^{h_{0}\beta}a^{h_{1}\beta}a_{p_{0}\beta}a^{p_{2}\beta}a_{h_{3}\beta}a_{h_{2}\beta}\delta^{p_{3}}_{p_{1}}
 + 1.0 * a^{h_{0}\beta}a^{h_{1}\beta}a_{p_{1}\beta}a^{p_{3}\beta}a_{h_{3}\beta}a_{h_{2}\beta}\delta^{p_{2}}_{p_{0}}
 + -1.0 * a^{h_{0}\beta}a^{h_{1}\beta}a_{p_{1}\beta}a^{p_{2}\beta}a_{

In [ ]:
def applyContractions(term, contractionsList):
    contractedTerm = copy(term)
    for c, contraction in enumerate(contractionsList):
        for v, vertex in reversed(list(enumerate(term.vertexList))):
            if contraction[0] in vertex.lowerIndices:
                contractedTerm.vertexList[v].lowerIndices[vertex.lowerIndices.index(contraction[0])] = contraction[1]
                break
            elif contraction[1] in vertex.upperIndices:
                contractedTerm.vertexList[v].upperIndices[vertex.upperIndices.index(contraction[1])] = contraction[0]
                break
    return contractedTerm

In [ ]:
print(testTensorProduct)

1.0 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{2}p_{3}}^{h_{2}h_{3}}


In [ ]:
testContractions = sumNFoldContractions(testTensorProduct.getOperator(spinFree=True).summandList[0], 1)

In [ ]:
print(applyContractions(testTensorProduct, testContractions.summandList[0].contractionsList))

1.0 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{2}p_{3}}^{h_{2}h_{0}}


In [ ]:
def evaluateTensorContractions(term, spinFree, nFreeIndexPairs, normalOrderedParts=True):
    '''
    Wick's theorem applied to a term

    input: term (TensorProduct)
    output: sum of n-fold contracted terms (TensorSum)
    '''
    if isinstance(term, TensorSum):
        return sum([evaluateTensorContractions(summand, spinFree, nFreeIndexPairs) for summand in term.summandList])
    summandList = []
    operator = term.getOperator(spinFree, normalOrderedParts)
    for summand in operator.summandList:
        nToContract = int(len(summand.operatorList) / 2) - nFreeIndexPairs
        if nToContract >= 0:
            contractions = sumNFoldContractions(summand, nToContract)
            for topology in contractions.summandList:
                contractionsList = topology.contractionsList
                contractedTerm = applyContractions(term, contractionsList)
                contractedTerm.prefactor *= topology.prefactor
                summandList.append(contractedTerm)
    return TensorSum(summandList)

In [ ]:
print(evaluateTensorContractions(testTensorProduct, True, 0))

1.0 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{1}p_{0}}^{h_{1}h_{0}}
 + -1.0 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{1}h_{0}}
 + -1.0 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{1}p_{0}}^{h_{0}h_{1}}
 + 1.0 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{0}h_{1}}
 + 1.0 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{0}h_{1}}
 + 1.0 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{1}p_{0}}^{h_{1}h_{0}}
 + 1.0 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{1}p_{0}}^{h_{1}h_{0}}
 + 1.0 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{0}h_{1}}
 + 1.0 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{1}p_{0}}^{h_{1}h_{0}}
 + -1.0 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{1}h_{0}}
 + -1.0 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{1}p_{0}}^{h_{0}h_{1}}
 + 1.0 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{0}h_{1}}


In [ ]:
print(evaluateWick(testTensorProduct, True))

4.0 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{1}p_{0}}^{h_{1}h_{0}}
 + -2.0 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{1}h_{0}}
 + -2.0 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{1}p_{0}}^{h_{0}h_{1}}
 + 4.0 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{0}h_{1}}


In [ ]:
BCHTransformedNormalOrderedHamiltonian

In [ ]:
len(BCHTransformedNormalOrderedHamiltonian.summandList)

620

In [ ]:
BCHTransformedNormalOrderedHamiltonian2 = BCHSimilarityTransform(normalOrderedHamiltonian, t2Tensor, 2)

In [ ]:
print(BCHTransformedNormalOrderedHamiltonian2)

1.0 * f_{h_{0}}^{h_{1}}
 + 1.0 * f_{h_{0}}^{p_{0}}
 + 1.0 * f_{p_{0}}^{h_{0}}
 + 1.0 * f_{p_{0}}^{p_{1}}
 + 0.5 * v_{h_{0}h_{1}}^{h_{2}h_{3}}
 + 0.5 * v_{h_{0}h_{1}}^{h_{2}p_{0}}
 + 0.5 * v_{h_{0}h_{1}}^{p_{0}h_{2}}
 + 0.5 * v_{h_{0}h_{1}}^{p_{0}p_{1}}
 + 0.5 * v_{h_{0}p_{0}}^{h_{1}h_{2}}
 + 0.5 * v_{h_{0}p_{0}}^{h_{1}p_{1}}
 + 0.5 * v_{h_{0}p_{0}}^{p_{1}h_{1}}
 + 0.5 * v_{h_{0}p_{0}}^{p_{1}p_{2}}
 + 0.5 * v_{p_{0}h_{0}}^{h_{1}h_{2}}
 + 0.5 * v_{p_{0}h_{0}}^{h_{1}p_{1}}
 + 0.5 * v_{p_{0}h_{0}}^{p_{1}h_{1}}
 + 0.5 * v_{p_{0}h_{0}}^{p_{1}p_{2}}
 + 0.5 * v_{p_{0}p_{1}}^{h_{0}h_{1}}
 + 0.5 * v_{p_{0}p_{1}}^{h_{0}p_{2}}
 + 0.5 * v_{p_{0}p_{1}}^{p_{2}h_{0}}
 + 0.5 * v_{p_{0}p_{1}}^{p_{2}p_{3}}
 + 1.0 * f_{h_{0}}^{h_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{2}h_{3}}
 + 1.0 * f_{h_{0}}^{p_{0}}{t_{2}}_{p_{1}p_{2}}^{h_{1}h_{2}}
 + 1.0 * f_{p_{0}}^{h_{0}}{t_{2}}_{p_{1}p_{2}}^{h_{1}h_{2}}
 + 1.0 * f_{p_{0}}^{p_{1}}{t_{2}}_{p_{2}p_{3}}^{h_{0}h_{1}}
 + 0.5 * v_{h_{0}h_{1}}^{h_{2}h_{3}}{t_{2}}_{p_{0}p_{1}}^{h_{4}

In [ ]:
len(BCHTransformedNormalOrderedHamiltonian2.summandList)

140

In [ ]:
len(BCHTransformedNormalOrderedHamiltonian2.getOperator(spinFree=False).summandList)

75

In [ ]:
len(BCHTransformedNormalOrderedHamiltonian2.getOperator(spinFree=True).summandList)

KeyboardInterrupt: 

In [ ]:
len(BCHTransformedNormalOrderedHamiltonian.summandList)

620

In [ ]:
len(BCHTransformedNormalOrderedHamiltonian.getOperator(spinFree=False).summandList)

185

In [ ]:
len(BCHTransformedNormalOrderedHamiltonian.getOperator(spinFree=True).summandList)

KeyboardInterrupt: 

In [ ]:
print(evaluateTensorContractions(BCHTransformedNormalOrderedHamiltonian2, False, 2))

KeyboardInterrupt: 

KeyboardInterrupt: 

In [ ]:
print(evaluateTensorContractions(BCHTransformedNormalOrderedHamiltonian.summandList[-1], True, 0))

KeyboardInterrupt: 

In [ ]:
CCDEnergyEquationTest = evaluateTensorContractions(BCHTransformedNormalOrderedHamiltonian, True, 0)

KeyboardInterrupt: 

In [ ]:
print(CCDEnergyEquationTest)

In [ ]:
CCDAmplitudeEquations = evaluateTensorContractions(BCHTransformedNormalOrderedHamiltonian, True, 2)

In [ ]:
def pairOrderedListsGenerator(list_):
    '''
    Given an ordered list with an even number of elements, returns list of all permutations of that list where each adjacent pair is ordered, and where the first elements of pairs are ordered
    !!!WOULD BE BETTER AS GENERATOR!!!
    '''
    pairOrderedLists = []
    if len(list_) == 2:
        pairOrderedLists.append(list_)
        yield list_
    else:
        for i in range(1,len(list_)):
            swappedList = [list_[0]] + [list_[i]] + list_[1:i]
            if i < len(list_):
                swappedList = swappedList + list_[i+1:]
            subListGenerator = pairOrderedListsGenerator(swappedList[2:])
            for subList in subListGenerator:
                yield swappedList[:2] + subList

Getting equations the old way

In [ ]:
CCDEnergyEquation = evaluateWick(BCHTransformedNormalOrderedHamiltonian, spinFree=True)

KeyboardInterrupt: 

In [ ]:
for summand in CCDEnergyEquation.summandList:
    summand.prefactor *= pow(0.5, len(summand.tensorList)-1)

In [ ]:
print(CCDEnergyEquation)

0.25 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{1}p_{0}}^{h_{1}h_{0}}
 + -0.125 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{1}h_{0}}
 + -0.125 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{1}p_{0}}^{h_{0}h_{1}}
 + 0.25 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{0}h_{1}}


In [ ]:
projectionDoubles = projectionManifold(2)

In [ ]:
ProjectedCCDAmplitudeEquation = evaluateWick(projectionDoubles * BCHTransformedNormalOrderedHamiltonian, spinFree=True)

In [ ]:
print(ProjectedCCDAmplitudeEquation)

2.0 * \Phi_{h_{0}h_{1}}^{p_{0}p_{1}}v_{p_{1}p_{0}}^{h_{1}h_{0}}
 + -1.0 * \Phi_{h_{0}h_{1}}^{p_{0}p_{1}}v_{p_{0}p_{1}}^{h_{1}h_{0}}
 + -1.0 * \Phi_{h_{0}h_{1}}^{p_{0}p_{1}}v_{p_{1}p_{0}}^{h_{0}h_{1}}
 + 2.0 * \Phi_{h_{0}h_{1}}^{p_{0}p_{1}}v_{p_{0}p_{1}}^{h_{0}h_{1}}
 + 0.5 * \Phi_{h_{0}h_{1}}^{p_{0}p_{1}}f_{h_{2}}^{h_{0}}{t_{2}}_{p_{1}p_{0}}^{h_{2}h_{1}}
 + -1.0 * \Phi_{h_{0}h_{1}}^{p_{0}p_{1}}f_{h_{2}}^{h_{0}}{t_{2}}_{p_{0}p_{1}}^{h_{2}h_{1}}
 + -1.0 * \Phi_{h_{0}h_{1}}^{p_{0}p_{1}}f_{h_{2}}^{h_{0}}{t_{2}}_{p_{1}p_{0}}^{h_{1}h_{2}}
 + 0.5 * \Phi_{h_{0}h_{1}}^{p_{0}p_{1}}f_{h_{2}}^{h_{0}}{t_{2}}_{p_{0}p_{1}}^{h_{1}h_{2}}
 + -1.0 * \Phi_{h_{0}h_{1}}^{p_{0}p_{1}}f_{h_{2}}^{h_{1}}{t_{2}}_{p_{1}p_{0}}^{h_{2}h_{0}}
 + 0.5 * \Phi_{h_{0}h_{1}}^{p_{0}p_{1}}f_{h_{2}}^{h_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{2}h_{0}}
 + 0.5 * \Phi_{h_{0}h_{1}}^{p_{0}p_{1}}f_{h_{2}}^{h_{1}}{t_{2}}_{p_{1}p_{0}}^{h_{0}h_{2}}
 + -1.0 * \Phi_{h_{0}h_{1}}^{p_{0}p_{1}}f_{h_{2}}^{h_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{0}h_{2}}
 + -0.5 *

In [ ]:
CCDAmplitudeEquation = copy(ProjectedCCDAmplitudeEquation)

In [ ]:
for summand in CCDAmplitudeEquation.summandList:
    summand.vertexList.pop(0)
    summand.tensorList.pop(0)

In [ ]:
print(CCDAmplitudeEquation)

2.0 * v_{p_{1}p_{0}}^{h_{1}h_{0}}
 + -1.0 * v_{p_{0}p_{1}}^{h_{1}h_{0}}
 + -1.0 * v_{p_{1}p_{0}}^{h_{0}h_{1}}
 + 2.0 * v_{p_{0}p_{1}}^{h_{0}h_{1}}
 + 0.5 * f_{h_{2}}^{h_{0}}{t_{2}}_{p_{1}p_{0}}^{h_{2}h_{1}}
 + -1.0 * f_{h_{2}}^{h_{0}}{t_{2}}_{p_{0}p_{1}}^{h_{2}h_{1}}
 + -1.0 * f_{h_{2}}^{h_{0}}{t_{2}}_{p_{1}p_{0}}^{h_{1}h_{2}}
 + 0.5 * f_{h_{2}}^{h_{0}}{t_{2}}_{p_{0}p_{1}}^{h_{1}h_{2}}
 + -1.0 * f_{h_{2}}^{h_{1}}{t_{2}}_{p_{1}p_{0}}^{h_{2}h_{0}}
 + 0.5 * f_{h_{2}}^{h_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{2}h_{0}}
 + 0.5 * f_{h_{2}}^{h_{1}}{t_{2}}_{p_{1}p_{0}}^{h_{0}h_{2}}
 + -1.0 * f_{h_{2}}^{h_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{0}h_{2}}
 + -0.5 * f_{p_{1}}^{p_{3}}{t_{2}}_{p_{0}p_{3}}^{h_{1}h_{0}}
 + 1.0 * f_{p_{1}}^{p_{3}}{t_{2}}_{p_{3}p_{0}}^{h_{1}h_{0}}
 + 1.0 * f_{p_{0}}^{p_{3}}{t_{2}}_{p_{1}p_{3}}^{h_{1}h_{0}}
 + -0.5 * f_{p_{0}}^{p_{3}}{t_{2}}_{p_{3}p_{1}}^{h_{1}h_{0}}
 + 1.0 * f_{p_{1}}^{p_{3}}{t_{2}}_{p_{0}p_{3}}^{h_{0}h_{1}}
 + -0.5 * f_{p_{1}}^{p_{3}}{t_{2}}_{p_{3}p_{0}}^{h_{0}h_{1}}
 + -0.

Storing equations as pickle file

In [ ]:
import pickle

In [ ]:
CCDEnergyEquation

In [ ]:
CCDEnergyEquation.summandList[0].

In [ ]:
with open("CCDEnergyEquation.pkl", "wb") as f:
    p = pickle.Pickler(f)
    for summand in CCDEnergyEquation.summandList:
        for tensor in summand.tensorList:
            p.dump(tensor)
        for vertex in summand.vertexList:
            for index in vertex.lowerIndices:
                p.dump(index)
            for index in vertex.upperIndices:
                p.dump(index)
            p.dump(vertex)
        p.dump(summand)
    p.dump(CCDEnergyEquation)

In [ ]:
with open("CCDAmplitudeEquation.pkl", "wb") as f:
    p = pickle.Pickler(f)
    for summand in CCDAmplitudeEquation.summandList:
        for tensor in summand.tensorList:
            p.dump(tensor)
        for vertex in summand.vertexList:
            for index in vertex.lowerIndices:
                p.dump(index)
            for index in vertex.upperIndices:
                p.dump(index)
            p.dump(vertex)
        p.dump(summand)
    p.dump(CCDAmplitudeEquation)

In [ ]:
with open("CCDEnergyEquation.pkl", "rb") as f:
    up = pickle.Unpickler(f)
    while True:
        up.load()
        if EOFError:
            break

In [ ]:
with open("CCDAmplitudeEquation.pkl", "rb") as f:
    up = pickle.Unpickler(f)
    while True:
        up.load()
        if EOFError:
            break

Test Equations

In [ ]:
bohr = 0.529177249

H2sep = 1.605 * bohr

mol = gto.Mole()
mol.verbose = 1
#mol.atom = 'Be 0 0 0'
#mol.basis = 'sto-3g'
mol.atom = 'H 0 0 0; H 0 0 ' + str(H2sep)
mol.basis = '6-31g'
mol.spin = 0
mol.build()

Enuc = mol.energy_nuc()

mf = scf.ROHF(mol)
mf.kernel()

cisolver = fci.FCI(mol, mf.mo_coeff)

Norbs = mol.nao
Nocc = mf.nelectron_alpha
vacuum = [1] * Nocc + [0] * (Norbs - Nocc)

h1 = mf.mo_coeff.T.dot(mf.get_hcore()).dot(mf.mo_coeff)
eri = ao2mo.kernel(mol, mf.mo_coeff, compact=False)

In [ ]:
from pyscf import cc, ccn

In [ ]:
trueCCD = cc.CCSD(mf).kernel()

In [ ]:
trueCCD

(-0.027549240513468364,
 (array([[ 4.96651012e-17,  8.78987007e-03, -3.14526443e-16]]),
  array([[ 9.46027408e-17,  8.78987007e-03, -3.29420687e-16]])),
 (array([[[[0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.]]]]),
  array([[[[-1.00108543e-01, -2.18342786e-16, -5.16134266e-02],
           [-1.45015766e-16, -4.53856765e-02, -3.12271178e-17],
           [-5.16134266e-02, -1.83154976e-17, -4.22705615e-02]]]]),
  array([[[[0., 0., 0.],
           [0., 0., 0.],
           [0., 0., 0.]]]])))

In [ ]:
trueAmplitudeArray = trueCCD[2][1].swapaxes(0,2).swapaxes(1,3)

In [ ]:
h1Tensor.array = h1
h2Tensor.array = eri.reshape((Norbs, Norbs, Norbs, Norbs)).swapaxes(2,3).swapaxes(1,2)
t2Tensor.getShape(vacuum)

In [ ]:
fock = h1
for p in range(Norbs):
    for q in range(Norbs):
        fock[p,q] += sum([2 * h2Tensor.array[p,i,q,i] - h2Tensor.array[p,i,i,q] for i in range(Nocc)])

In [ ]:
fockTensor.array = fock

In [ ]:
fockTensor.assignDiagramArrays(vacuum)
h2Tensor.assignDiagramArrays(vacuum)

In [ ]:
CCDEnergy = contractTensorSum(CCDEnergyEquation)
print(CCDEnergy)

0.0


In [ ]:
residual = contractTensorSum(CCDAmplitudeEquation)
print(residual)

[[[[1.83496817e-01]]

  [[6.13572032e-16]]

  [[1.61809044e-01]]]


 [[[6.13572032e-16]]

  [[2.06650292e-01]]

  [[2.26090247e-16]]]


 [[[1.61809044e-01]]

  [[2.26090247e-16]]

  [[2.52252235e-01]]]]


In [ ]:
residualTensor = Tensor("R", ['p', 'p'], ['h', 'h'])
residualTensor.getShape(vacuum)

In [ ]:
def iterateDoublesAmplitudes(doublesTensor, residual):
    amplitudes = doublesTensor.array
    for i in range(amplitudes.shape[0]):
        for j in range(amplitudes.shape[1]):
            for k in range(amplitudes.shape[2]):
                for l in range(amplitudes.shape[3]):
#                    mp2Amplitudes[i,j,k,l] = (2 - (i==j)) * residual.array[i,j,k,l] / (fock[i + Nocc, i + Nocc] + fock[j + Nocc, j + Nocc] - fock[k, k] - fock[l, l])
                    amplitudes[i,j,k,l] -= residual.array[i,j,k,l] / (fock[i + Nocc, i + Nocc] + fock[j + Nocc, j + Nocc] - fock[k, k] - fock[l, l])
    return amplitudes

In [ ]:
def convergeDoublesAmplitudes():
    t2Tensor.array = np.zeros_like(t2Tensor.array)
#    t2Tensor.array = trueAmplitudeArray
    Energy = contractTensorSum(CCDEnergyEquation)
    residualTensor.array = h2Tensor.diagrams[12].array
    while True:
        print(Energy)
        t2Tensor.array = iterateDoublesAmplitudes(t2Tensor, residualTensor)
        residualTensor.array = contractTensorSum(CCDAmplitudeEquation)
        Energy = contractTensorSum(CCDEnergyEquation)
#        newEnergy = getCCDEnergy(t2Tensor)
#        if abs(newEnergy - Energy) < 0.00000001:
        if np.all(abs(residualTensor.array) < 0.00000000000001):
            break
#        Energy = newEnergy
    print(Energy)
    print(t2Tensor.array)

In [ ]:
convergeDoublesAmplitudes()

0.0
-0.009291639221900176
-0.021498011408527112
-0.025314227424464715
-0.026609321883791635
-0.027082108450811382
-0.02726368171760967
-0.02733562687578168
-0.02736465389594942
-0.02737648476307522
-0.027381334108486664
-0.02738332803808354
-0.027384149321699407
-0.02738448793169186
-0.02738462761510998
-0.027384685255300207
-0.027384709044708248
-0.027384718864151985
-0.027384722917524792
-0.027384724590779043
-0.027384725281522568
-0.027384725566675316
-0.02738472568439307
-0.02738472573298999
-0.02738472575305212
-0.027384725761334335
-0.027384725764753468
-0.027384725766164984
-0.027384725766747706
-0.02738472576698827
-0.027384725767087583
-0.02738472576712858
-0.027384725767145505
-0.027384725767152493
-0.027384725767155373
-0.027384725767156573
-0.02738472576715706
[[[[-2.00301516e-01]]

  [[-4.36621248e-16]]

  [[-1.01968056e-01]]]


 [[[-4.43451492e-16]]

  [[-9.13439240e-02]]

  [[-7.75392564e-17]]]


 [[[-1.01968056e-01]]

  [[-6.83202299e-17]]

  [[-8.28902730e-02]]]]


In [ ]:
from pyscf import mp

In [ ]:
trueMP2 = mp.MP2(mf)

In [ ]:
trueMP2.kernel()

(-0.018583278498233484,
 (array([[[[ 0.00000000e+00, -5.58292846e-17, -4.85722573e-17],
           [ 5.58292846e-17,  0.00000000e+00, -1.52098642e-17],
           [ 4.85722573e-17,  1.52098642e-17,  0.00000000e+00]]]]),
  array([[[[-5.93124735e-02, -1.72511867e-16, -3.08991295e-02],
           [-1.16682582e-16, -3.70716082e-02, -4.73681065e-17],
           [-3.08991295e-02, -3.21582423e-17, -3.41821791e-02]]]]),
  array([[[[ 0.00000000e+00, -5.58292846e-17, -4.85722573e-17],
           [ 5.58292846e-17,  0.00000000e+00, -1.52098642e-17],
           [ 4.85722573e-17,  1.52098642e-17,  0.00000000e+00]]]])))

CCSD

In [14]:
t1Tensor = Tensor("{t_{1}}", ['p'], ['h'])

In [15]:
projectionSingles = projectionManifold(1)
projectionDoubles = projectionManifold(2)

In [16]:
CCSDBCHTransformedNormalOrderedHamiltonian = BCHSimilarityTransform(normalOrderedHamiltonian, t1Tensor + 0.25 * t2Tensor, 4)

In [17]:
CCSDEnergyEquation = evaluateWick(CCSDBCHTransformedNormalOrderedHamiltonian, True)

In [18]:
projectedSinglesCCSDAmplitudeEquation = evaluateWick(projectionSingles * CCSDBCHTransformedNormalOrderedHamiltonian, spinFree=True)
projectedDoublesCCSDAmplitudeEquation = evaluateWick(projectionDoubles * CCSDBCHTransformedNormalOrderedHamiltonian, spinFree=True)

In [ ]:
singlesCCSDAmplitudeEquation = copy(projectedSinglesCCSDAmplitudeEquation)
doublesCCSDAmplitudeEquation = copy(projectedDoublesCCSDAmplitudeEquation)

In [ ]:
for summand in singlesCCSDAmplitudeEquation.summandList:
    summand.vertexList.pop(0)
    summand.tensorList.pop(0)
for summand in doublesCCSDAmplitudeEquation.summandList:
    summand.vertexList.pop(0)
    summand.tensorList.pop(0)

In [ ]:
singlesResidualTensor = Tensor("R", ['p'], ['h'])
singlesResidualTensor.getShape(vacuum)
doublesResidualTensor = Tensor("R", ['p', 'p'], ['h', 'h'])
doublesResidualTensor.getShape(vacuum)

In [ ]:
def iterateSinglesAmplitudes(singlesTensor, residual):
    amplitudes = singlesTensor.array
    for i in range(amplitudes.shape[0]):
        for j in range(amplitudes.shape[1]):
            amplitudes[i,j] -= residual.array[i,j] / (fock[i + Nocc, i + Nocc] - fock[j, j])
    return amplitudes

In [ ]:
def convergeCCSDAmplitudes():
    t2Tensor.array = np.zeros_like(t2Tensor.array)
#    t2Tensor.array = trueAmplitudeArray
    Energy = contractTensorSum(CCDEnergyEquation)
    residualTensor.array = h2Tensor.diagrams[12].array
    while True:
        print(Energy)
        t2Tensor.array = iterateDoublesAmplitudes(t2Tensor, residualTensor)
        residualTensor.array = contractTensorSum(CCDAmplitudeEquation)
        Energy = contractTensorSum(CCDEnergyEquation)
#        newEnergy = getCCDEnergy(t2Tensor)
#        if abs(newEnergy - Energy) < 0.00000001:
        if np.all(abs(residualTensor.array) < 0.00000000000001):
            break
#        Energy = newEnergy
    print(Energy)
    print(t2Tensor.array)