In [1]:
from time import time
from GeneralisedWick import *
import CC, texify, pickle

In [2]:
fockTensor = Tensor("f", ['g'], ['g'])
h2Tensor = Tensor("v", ['g', 'g'], ['g', 'g'])

fockTensor.getAllDiagramsGeneral()
h2Tensor.getAllDiagramsGeneral()

t1Tensor = Tensor("{t_{1}}", ['p'], ['h'])
t2Tensor = Tensor("{t_{2}}", ['p', 'p'], ['h', 'h'])

In [3]:
normalOrderedHamiltonian = sum(fockTensor.diagrams) + (1. / 2.) * sum(h2Tensor.diagrams)
#BCH = CC.BCHSimilarityTransform(normalOrderedHamiltonian, t1Tensor + 0.25 * t2Tensor, 4)
BCH = CC.BCHSimilarityTransform(normalOrderedHamiltonian, 0.25 * t2Tensor, 4)

In [4]:
energyEquation = CC.getEnergyEquation(BCH, spinFree=False)

In [5]:
print(energyEquation)

0.25 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{1}p_{0}}^{h_{1}h_{0}}
 + -0.25 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{1}h_{0}}


In [6]:
print(energyEquation.collectIsomorphicTerms())

0.25 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{1}p_{0}}^{h_{1}h_{0}}
 + -0.25 * v_{h_{0}h_{1}}^{p_{0}p_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{1}h_{0}}


In [7]:
singlesAmplitudeEquation = CC.getAmplitudeEquation(BCH, 1, spinFree=False)

In [8]:
print(singlesAmplitudeEquation)

1.0 * f_{p_{0}}^{h_{0}}
 + -0.5 * f_{h_{1}}^{p_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{1}h_{0}}
 + 0.5 * f_{h_{1}}^{p_{1}}{t_{2}}_{p_{1}p_{0}}^{h_{1}h_{0}}
 + 0.5 * v_{h_{1}h_{2}}^{h_{0}p_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{2}h_{1}}
 + -0.5 * v_{h_{1}h_{2}}^{h_{0}p_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{1}h_{2}}
 + -0.5 * v_{h_{1}p_{0}}^{p_{2}p_{3}}{t_{2}}_{p_{3}p_{2}}^{h_{1}h_{0}}
 + 0.5 * v_{h_{1}p_{0}}^{p_{2}p_{3}}{t_{2}}_{p_{2}p_{3}}^{h_{1}h_{0}}


In [9]:
doublesAmplitudeEquation = CC.getAmplitudeEquation(BCH, 2, spinFree=False)

In [10]:
projection = CC.projectionManifold(2)
projectedAmplitudeEquation = evaluateWick(projection * BCH, spinFree=False)
#amplitudeEquation = copy(projectedAmplitudeEquation).collectIsomorphicTerms()
amplitudeEquation = copy(projectedAmplitudeEquation)
for summand in amplitudeEquation.summandList:
    summand.tensorList.pop(0)
    summand.vertexList.pop(0)
print(amplitudeEquation)

0.5 * v_{p_{1}p_{0}}^{h_{1}h_{0}}
 + -0.5 * v_{p_{0}p_{1}}^{h_{1}h_{0}}
 + -0.5 * v_{p_{1}p_{0}}^{h_{0}h_{1}}
 + 0.5 * v_{p_{0}p_{1}}^{h_{0}h_{1}}
 + 0.25 * f_{h_{2}}^{h_{0}}{t_{2}}_{p_{1}p_{0}}^{h_{2}h_{1}}
 + -0.25 * f_{h_{2}}^{h_{0}}{t_{2}}_{p_{0}p_{1}}^{h_{2}h_{1}}
 + -0.25 * f_{h_{2}}^{h_{0}}{t_{2}}_{p_{1}p_{0}}^{h_{1}h_{2}}
 + 0.25 * f_{h_{2}}^{h_{0}}{t_{2}}_{p_{0}p_{1}}^{h_{1}h_{2}}
 + -0.25 * f_{h_{2}}^{h_{1}}{t_{2}}_{p_{1}p_{0}}^{h_{2}h_{0}}
 + 0.25 * f_{h_{2}}^{h_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{2}h_{0}}
 + 0.25 * f_{h_{2}}^{h_{1}}{t_{2}}_{p_{1}p_{0}}^{h_{0}h_{2}}
 + -0.25 * f_{h_{2}}^{h_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{0}h_{2}}
 + -0.25 * f_{p_{1}}^{p_{3}}{t_{2}}_{p_{0}p_{3}}^{h_{1}h_{0}}
 + 0.25 * f_{p_{1}}^{p_{3}}{t_{2}}_{p_{3}p_{0}}^{h_{1}h_{0}}
 + 0.25 * f_{p_{0}}^{p_{3}}{t_{2}}_{p_{1}p_{3}}^{h_{1}h_{0}}
 + -0.25 * f_{p_{0}}^{p_{3}}{t_{2}}_{p_{3}p_{1}}^{h_{1}h_{0}}
 + 0.25 * f_{p_{1}}^{p_{3}}{t_{2}}_{p_{0}p_{3}}^{h_{0}h_{1}}
 + -0.25 * f_{p_{1}}^{p_{3}}{t_{2}}_{p_{3}p_{0}}^{h_{0

In [11]:
collectedAmplitudeEquation = copy(projectedAmplitudeEquation).collectIsomorphicTerms()
for summand in collectedAmplitudeEquation.summandList:
    summand.tensorList.pop(0)
    summand.vertexList.pop(0)
print(collectedAmplitudeEquation)

1.0 * v_{p_{1}p_{0}}^{h_{1}h_{0}}
 + -1.0 * v_{p_{0}p_{1}}^{h_{1}h_{0}}
 + 0.5 * f_{h_{2}}^{h_{0}}{t_{2}}_{p_{1}p_{0}}^{h_{2}h_{1}}
 + -0.5 * f_{h_{2}}^{h_{0}}{t_{2}}_{p_{0}p_{1}}^{h_{2}h_{1}}
 + -0.5 * f_{h_{2}}^{h_{1}}{t_{2}}_{p_{1}p_{0}}^{h_{2}h_{0}}
 + 0.5 * f_{h_{2}}^{h_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{2}h_{0}}
 + -0.5 * f_{p_{1}}^{p_{3}}{t_{2}}_{p_{0}p_{3}}^{h_{1}h_{0}}
 + 0.5 * f_{p_{1}}^{p_{3}}{t_{2}}_{p_{3}p_{0}}^{h_{1}h_{0}}
 + 0.5 * f_{p_{0}}^{p_{3}}{t_{2}}_{p_{1}p_{3}}^{h_{1}h_{0}}
 + -0.5 * f_{p_{0}}^{p_{3}}{t_{2}}_{p_{3}p_{1}}^{h_{1}h_{0}}
 + -0.5 * v_{h_{2}h_{3}}^{h_{1}h_{0}}{t_{2}}_{p_{1}p_{0}}^{h_{3}h_{2}}
 + 0.5 * v_{h_{2}h_{3}}^{h_{1}h_{0}}{t_{2}}_{p_{1}p_{0}}^{h_{2}h_{3}}
 + -0.5 * v_{h_{2}p_{1}}^{h_{0}p_{3}}{t_{2}}_{p_{0}p_{3}}^{h_{2}h_{1}}
 + 0.5 * v_{h_{2}p_{1}}^{h_{0}p_{3}}{t_{2}}_{p_{3}p_{0}}^{h_{2}h_{1}}
 + 0.5 * v_{h_{2}p_{0}}^{h_{0}p_{3}}{t_{2}}_{p_{1}p_{3}}^{h_{2}h_{1}}
 + -0.5 * v_{h_{2}p_{0}}^{h_{0}p_{3}}{t_{2}}_{p_{3}p_{1}}^{h_{2}h_{1}}
 + 0.5 * v_{h_{2}p_{1

In [12]:
print(doublesAmplitudeEquation)

1.0 * v_{p_{1}p_{0}}^{h_{1}h_{0}}
 + -1.0 * v_{p_{0}p_{1}}^{h_{1}h_{0}}
 + 0.5 * f_{h_{2}}^{h_{0}}{t_{2}}_{p_{1}p_{0}}^{h_{2}h_{1}}
 + -0.5 * f_{h_{2}}^{h_{0}}{t_{2}}_{p_{0}p_{1}}^{h_{2}h_{1}}
 + -0.5 * f_{h_{2}}^{h_{1}}{t_{2}}_{p_{1}p_{0}}^{h_{2}h_{0}}
 + 0.5 * f_{h_{2}}^{h_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{2}h_{0}}
 + -0.5 * f_{p_{1}}^{p_{3}}{t_{2}}_{p_{0}p_{3}}^{h_{1}h_{0}}
 + 0.5 * f_{p_{1}}^{p_{3}}{t_{2}}_{p_{3}p_{0}}^{h_{1}h_{0}}
 + 0.5 * f_{p_{0}}^{p_{3}}{t_{2}}_{p_{1}p_{3}}^{h_{1}h_{0}}
 + -0.5 * f_{p_{0}}^{p_{3}}{t_{2}}_{p_{3}p_{1}}^{h_{1}h_{0}}
 + -0.5 * v_{h_{2}h_{3}}^{h_{1}h_{0}}{t_{2}}_{p_{1}p_{0}}^{h_{3}h_{2}}
 + 0.5 * v_{h_{2}h_{3}}^{h_{1}h_{0}}{t_{2}}_{p_{1}p_{0}}^{h_{2}h_{3}}
 + -0.5 * v_{h_{2}p_{1}}^{h_{0}p_{3}}{t_{2}}_{p_{0}p_{3}}^{h_{2}h_{1}}
 + 0.5 * v_{h_{2}p_{1}}^{h_{0}p_{3}}{t_{2}}_{p_{3}p_{0}}^{h_{2}h_{1}}
 + 0.5 * v_{h_{2}p_{0}}^{h_{0}p_{3}}{t_{2}}_{p_{1}p_{3}}^{h_{2}h_{1}}
 + -0.5 * v_{h_{2}p_{0}}^{h_{0}p_{3}}{t_{2}}_{p_{3}p_{1}}^{h_{2}h_{1}}
 + 0.5 * v_{h_{2}p_{1

In [13]:
len(doublesAmplitudeEquation.summandList)

68

In [14]:
bohr = 0.529177249

H2sep = 1.605 * bohr

mol = gto.Mole()
mol.verbose = 1
mol.atom = 'Be 0 0 0'
#mol.basis = 'sto-3g'
#mol.atom = 'H 0 0 0; H 0 0 ' + str(H2sep)
mol.basis = '6-31g'
mol.spin = 0
mol.build()

In [15]:
mol.energy_nuc()

0

In [16]:
mf = scf.ROHF(mol)
mf.kernel()

-14.56676403350963

In [17]:
mol.nao

9

In [18]:
mf.get_fock()

NPArrayWithTag([[-4.70627323, -0.94754316, -1.01375577,  0.        ,
                  0.        ,  0.        ,  0.        ,  0.        ,
                  0.        ],
                [-0.94754316, -0.38227341, -0.49222055,  0.        ,
                  0.        ,  0.        ,  0.        ,  0.        ,
                  0.        ],
                [-1.01375577, -0.49222055, -0.49242135,  0.        ,
                  0.        ,  0.        ,  0.        ,  0.        ,
                  0.        ],
                [ 0.        ,  0.        ,  0.        ,  0.21892424,
                  0.        ,  0.        ,  0.01030321,  0.        ,
                  0.        ],
                [ 0.        ,  0.        ,  0.        ,  0.        ,
                  0.21892424,  0.        ,  0.        ,  0.01030321,
                  0.        ],
                [ 0.        ,  0.        ,  0.        ,  0.        ,
                  0.        ,  0.21892424,  0.        ,  0.        ,
                 

In [19]:
mf.get_hcore()

array([[-7.94596617, -1.3281734 , -1.52567345,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [-1.3281734 , -1.97116759, -1.72607938,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [-1.52567345, -1.72607938, -1.70782077,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , -1.71278859,  0.        ,
         0.        , -0.9912575 ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        , -1.71278859,
         0.        ,  0.        , -0.9912575 ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        -1.71278859,  0.        ,  0.        , -0.9912575 ],
       [ 0.        ,  0.        ,  0.        , -0.9912575 ,  0.        ,
         0.        , -1.01508233,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        , -0

In [20]:
cisolver = fci.FCI(mol, mf.mo_coeff)

Norbs = mol.nao
Nocc = mf.nelectron_alpha
vacuum = [1] * Nocc + [0] * (Norbs - Nocc)

h1 = mf.mo_coeff.T.dot(mf.get_hcore()).dot(mf.mo_coeff)
eri = ao2mo.kernel(mol, mf.mo_coeff, compact=False)

h2Tensor.array = eri.reshape((Norbs, Norbs, Norbs, Norbs)).swapaxes(2,3).swapaxes(1,2)

fock = h1
for p in range(Norbs):
    for q in range(Norbs):
        fock[p,q] += sum([2 * h2Tensor.array[p,i,q,i] - h2Tensor.array[p,i,i,q] for i in range(Nocc)])
fockTensor.array = fock

fockTensor.assignDiagramArrays(vacuum)
h2Tensor.assignDiagramArrays(vacuum)
t2Tensor.getShape(vacuum)

In [21]:
mf.mo_coeff.T.dot(mf.get_fock()).dot(mf.mo_coeff)

array([[-4.70689051e+00,  5.31284660e-11,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  3.21473226e-11,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 5.31285676e-11, -3.01295386e-01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  8.48784212e-10,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  8.24353414e-02,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -6.09065488e-10,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         8.24353414e-02,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -6.09065494e-10],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  8.24353414e-02,  0.00000000e+00,
         0.00000000e+00, -6.09065494e-10,  0.00000000e+00],
       [ 3.21472868e-11,  8.48784429e-10,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  4.397543

In [22]:
fock

array([[-4.70689051e+00,  5.31283906e-11,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  3.21496441e-11,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 5.31285016e-11, -3.01295386e-01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  8.48783932e-10,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  8.24353414e-02,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        -6.09065243e-10,  0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         8.24353414e-02,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00, -6.09065409e-10],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  8.24353414e-02,  0.00000000e+00,
         0.00000000e+00, -6.09065409e-10,  0.00000000e+00],
       [ 3.21496163e-11,  8.48783821e-10,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  4.397543

In [23]:
fock.shape

(9, 9)

In [24]:
fock.shape * 2

(9, 9, 9, 9)

In [25]:
def orb2spinorb(tensor):
    array = tensor.array
    print(array.shape)
    newArray = np.zeros(tuple(2 * d for d in array.shape))
    print(newArray.shape)
    for indices, element in np.ndenumerate(array):
        newIndices = tuple(2 * d for d in indices)
        print(indices, newIndices)
#        newArray[newIndices] = element
        for nAxes in range(len(array.shape)):
            for axesCombination in itertools.combinations(range(int(0.5 * len(array.shape))), nAxes):
                print(axesCombination)
                print(len(array.shape))
                newIndicesExtra = tuple([newIndex + (nI in axesCombination or (nI - int(0.5 * len(array.shape))) in axesCombination) for nI, newIndex in enumerate(newIndices)])
                print(newIndicesExtra)
                newArray[newIndicesExtra] = element
    tensor.array = newArray

In [26]:
orb2spinorb(fockTensor)

(9, 9)
(18, 18)
(0, 0) (0, 0)
()
2
(0, 0)
(0,)
2
(1, 1)
(0, 1) (0, 2)
()
2
(0, 2)
(0,)
2
(1, 3)
(0, 2) (0, 4)
()
2
(0, 4)
(0,)
2
(1, 5)
(0, 3) (0, 6)
()
2
(0, 6)
(0,)
2
(1, 7)
(0, 4) (0, 8)
()
2
(0, 8)
(0,)
2
(1, 9)
(0, 5) (0, 10)
()
2
(0, 10)
(0,)
2
(1, 11)
(0, 6) (0, 12)
()
2
(0, 12)
(0,)
2
(1, 13)
(0, 7) (0, 14)
()
2
(0, 14)
(0,)
2
(1, 15)
(0, 8) (0, 16)
()
2
(0, 16)
(0,)
2
(1, 17)
(1, 0) (2, 0)
()
2
(2, 0)
(0,)
2
(3, 1)
(1, 1) (2, 2)
()
2
(2, 2)
(0,)
2
(3, 3)
(1, 2) (2, 4)
()
2
(2, 4)
(0,)
2
(3, 5)
(1, 3) (2, 6)
()
2
(2, 6)
(0,)
2
(3, 7)
(1, 4) (2, 8)
()
2
(2, 8)
(0,)
2
(3, 9)
(1, 5) (2, 10)
()
2
(2, 10)
(0,)
2
(3, 11)
(1, 6) (2, 12)
()
2
(2, 12)
(0,)
2
(3, 13)
(1, 7) (2, 14)
()
2
(2, 14)
(0,)
2
(3, 15)
(1, 8) (2, 16)
()
2
(2, 16)
(0,)
2
(3, 17)
(2, 0) (4, 0)
()
2
(4, 0)
(0,)
2
(5, 1)
(2, 1) (4, 2)
()
2
(4, 2)
(0,)
2
(5, 3)
(2, 2) (4, 4)
()
2
(4, 4)
(0,)
2
(5, 5)
(2, 3) (4, 6)
()
2
(4, 6)
(0,)
2
(5, 7)
(2, 4) (4, 8)
()
2
(4, 8)
(0,)
2
(5, 9)
(2, 5) (4, 10)
()
2
(4, 10)
(0,)
2
(5, 1

In [27]:
orb2spinorb(h2Tensor)

(9, 9, 9, 9)
(18, 18, 18, 18)
(0, 0, 0, 0) (0, 0, 0, 0)
()
4
(0, 0, 0, 0)
(0,)
4
(1, 0, 1, 0)
(1,)
4
(0, 1, 0, 1)
(0, 1)
4
(1, 1, 1, 1)
(0, 0, 0, 1) (0, 0, 0, 2)
()
4
(0, 0, 0, 2)
(0,)
4
(1, 0, 1, 2)
(1,)
4
(0, 1, 0, 3)
(0, 1)
4
(1, 1, 1, 3)
(0, 0, 0, 2) (0, 0, 0, 4)
()
4
(0, 0, 0, 4)
(0,)
4
(1, 0, 1, 4)
(1,)
4
(0, 1, 0, 5)
(0, 1)
4
(1, 1, 1, 5)
(0, 0, 0, 3) (0, 0, 0, 6)
()
4
(0, 0, 0, 6)
(0,)
4
(1, 0, 1, 6)
(1,)
4
(0, 1, 0, 7)
(0, 1)
4
(1, 1, 1, 7)
(0, 0, 0, 4) (0, 0, 0, 8)
()
4
(0, 0, 0, 8)
(0,)
4
(1, 0, 1, 8)
(1,)
4
(0, 1, 0, 9)
(0, 1)
4
(1, 1, 1, 9)
(0, 0, 0, 5) (0, 0, 0, 10)
()
4
(0, 0, 0, 10)
(0,)
4
(1, 0, 1, 10)
(1,)
4
(0, 1, 0, 11)
(0, 1)
4
(1, 1, 1, 11)
(0, 0, 0, 6) (0, 0, 0, 12)
()
4
(0, 0, 0, 12)
(0,)
4
(1, 0, 1, 12)
(1,)
4
(0, 1, 0, 13)
(0, 1)
4
(1, 1, 1, 13)
(0, 0, 0, 7) (0, 0, 0, 14)
()
4
(0, 0, 0, 14)
(0,)
4
(1, 0, 1, 14)
(1,)
4
(0, 1, 0, 15)
(0, 1)
4
(1, 1, 1, 15)
(0, 0, 0, 8) (0, 0, 0, 16)
()
4
(0, 0, 0, 16)
(0,)
4
(1, 0, 1, 16)
(1,)
4
(0, 1, 0, 17)
(0, 1)
4
(1, 1, 1, 

In [28]:
print(t2Tensor.array.shape)
print(fockTensor.array.shape)
print(h2Tensor.array.shape)

(7, 7, 2, 2)
(18, 18)
(18, 18, 18, 18)


In [29]:
print(fock)
print(fockTensor.array)

[[-4.70689051e+00  5.31283906e-11  0.00000000e+00  0.00000000e+00
   0.00000000e+00  3.21496441e-11  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 5.31285016e-11 -3.01295386e-01  0.00000000e+00  0.00000000e+00
   0.00000000e+00  8.48783932e-10  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  8.24353414e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00 -6.09065243e-10  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  8.24353414e-02
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -6.09065409e-10]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   8.24353414e-02  0.00000000e+00  0.00000000e+00 -6.09065409e-10
   0.00000000e+00]
 [ 3.21496163e-11  8.48783821e-10  0.00000000e+00  0.00000000e+00
   0.00000000e+00  4.39754310e-01  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -6.09065354e-10  0.00000000e+00
   0.00000000e+00  0.0000000

In [30]:
fockTensor.array = fock
print(fockTensor.array)
orb2spinorb(fockTensor)
print(fockTensor.array)

[[-4.70689051e+00  5.31283906e-11  0.00000000e+00  0.00000000e+00
   0.00000000e+00  3.21496441e-11  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 5.31285016e-11 -3.01295386e-01  0.00000000e+00  0.00000000e+00
   0.00000000e+00  8.48783932e-10  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  8.24353414e-02  0.00000000e+00
   0.00000000e+00  0.00000000e+00 -6.09065243e-10  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  8.24353414e-02
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
  -6.09065409e-10]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   8.24353414e-02  0.00000000e+00  0.00000000e+00 -6.09065409e-10
   0.00000000e+00]
 [ 3.21496163e-11  8.48783821e-10  0.00000000e+00  0.00000000e+00
   0.00000000e+00  4.39754310e-01  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -6.09065354e-10  0.00000000e+00
   0.00000000e+00  0.0000000

In [31]:
h2Tensor.array = eri.reshape((Norbs, Norbs, Norbs, Norbs)).swapaxes(2,3).swapaxes(1,2)
print(h2Tensor.array)
orb2spinorb(h2Tensor)
print(h2Tensor.array)

[[[[ 2.27130649e+00 -1.99969155e-01  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [-1.99969155e-01  2.83882044e-02  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  3.30086167e-03 ...  9.35905544e-03
     0.00000000e+00  0.00000000e+00]
   ...
   [ 0.00000000e+00  0.00000000e+00  9.35905544e-03 ...  2.69900982e-02
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     2.69900982e-02  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  2.69900982e-02]]

  [[-1.99969155e-01  4.95347745e-01  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 2.83882044e-02 -6.66823217e-03  0.00000000e+00 ...  0.00000000e+00
     0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  6.59818153e-03 ...  6.73647539e-03
     0.00000000e+00  0.00000000e+00]
   ...
   

In [32]:
vacuumSpinOrb = [1] * (2 * Nocc) + [0] * (2 * (Norbs - Nocc))

In [33]:
vacuumSpinOrb

[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [34]:
fockTensor.assignDiagramArrays(vacuumSpinOrb)
h2Tensor.assignDiagramArrays(vacuumSpinOrb)
t1Tensor.getShape(vacuumSpinOrb)
t2Tensor.getShape(vacuumSpinOrb)

In [35]:
t2Tensor.array

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        ...,

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0

In [36]:
contractTensorSum(energyEquation)

0.0

In [37]:
residualTensor = Tensor("R", ['p', 'p'], ['h', 'h'])
residualTensor.array = contractTensorSum(amplitudeEquation)

In [38]:
residualTensor.array

array([[[[ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ]],

        [[ 0.        ,  0.00330086,  0.        ,  0.00659818],
         [-0.00330086,  0.        , -0.00659818,  0.        ],
         [ 0.        ,  0.00659818,  0.        ,  0.063035  ],
         [-0.00659818,  0.        , -0.063035  ,  0.        ]],

        [[ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ]],

        ...,

        [[ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,

In [39]:
getContractedArray(doublesAmplitudeEquation.summandList[10])

(array([[[[-0., -0., -0., -0.],
          [-0., -0., -0., -0.],
          [-0., -0., -0., -0.],
          [-0., -0., -0., -0.]],
 
         [[-0., -0., -0., -0.],
          [-0., -0., -0., -0.],
          [-0., -0., -0., -0.],
          [-0., -0., -0., -0.]],
 
         [[-0., -0., -0., -0.],
          [-0., -0., -0., -0.],
          [-0., -0., -0., -0.],
          [-0., -0., -0., -0.]],
 
         ...,
 
         [[-0., -0., -0., -0.],
          [-0., -0., -0., -0.],
          [-0., -0., -0., -0.],
          [-0., -0., -0., -0.]],
 
         [[-0., -0., -0., -0.],
          [-0., -0., -0., -0.],
          [-0., -0., -0., -0.],
          [-0., -0., -0., -0.]],
 
         [[-0., -0., -0., -0.],
          [-0., -0., -0., -0.],
          [-0., -0., -0., -0.],
          [-0., -0., -0., -0.]]],
 
 
        [[[-0., -0., -0., -0.],
          [-0., -0., -0., -0.],
          [-0., -0., -0., -0.],
          [-0., -0., -0., -0.]],
 
         [[-0., -0., -0., -0.],
          [-0., -0., -0., -0.],


In [40]:
t2Tensor.array = np.zeros_like(t2Tensor.array)

In [41]:
contractTensorSum(collectedAmplitudeEquation)

array([[[[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00]],

        [[ 0.00000000e+00,  3.30086167e-03,  0.00000000e+00,
           6.59818153e-03],
         [-3.30086167e-03,  0.00000000e+00, -6.59818153e-03,
           0.00000000e+00],
         [ 0.00000000e+00,  6.59818153e-03,  0.00000000e+00,
           6.30349976e-02],
         [-6.59818153e-03,  0.00000000e+00, -6.30349976e-02,
           0.00000000e+00]],

        [[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00],
         [ 0.0000

In [42]:
residualTensor.array

array([[[[ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ]],

        [[ 0.        ,  0.00330086,  0.        ,  0.00659818],
         [-0.00330086,  0.        , -0.00659818,  0.        ],
         [ 0.        ,  0.00659818,  0.        ,  0.063035  ],
         [-0.00659818,  0.        , -0.063035  ,  0.        ]],

        [[ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ]],

        ...,

        [[ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,

In [43]:
residualTensor.array.shape

(14, 14, 4, 4)

In [44]:
t2Tensor.array.shape

(14, 14, 4, 4)

In [45]:
CC.iterateDoublesAmplitudes(t2Tensor, residualTensor, fockTensor.array, False)

array([[[[ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ]],

        [[ 0.        , -0.00034461,  0.        , -0.00127549],
         [ 0.00034461,  0.        ,  0.00127549,  0.        ],
         [ 0.        , -0.00127549,  0.        , -0.08213441],
         [ 0.00127549,  0.        ,  0.08213441,  0.        ]],

        [[ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ]],

        ...,

        [[ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,

In [46]:
contractTensorSum(energyEquation)

-0.0243110108197627

In [47]:
def convergeDoublesAmplitudes(doublesTensor, CCDEnergyEquation, CCDAmplitudeEquation, fockTensor, spinFree=True):
    residualTensor = Tensor("R", ['p', 'p'], ['h', 'h'])
    doublesTensor.array = np.zeros_like(doublesTensor.array)
    Energy = contractTensorSum(CCDEnergyEquation)
    residualTensor.array = contractTensorSum(CCDAmplitudeEquation)
#    residualTensor.array = (1./3.) * residualTensor.array + (1./6.) * residualTensor.array.swapaxes(0,1)
    print(residualTensor.array)
    while True:
        print(Energy)
        doublesTensor.array = CC.iterateDoublesAmplitudes(doublesTensor, residualTensor, fockTensor.array, spinFree)
        residualTensor.array = contractTensorSum(CCDAmplitudeEquation)
#        residualTensor.array = (1./3.) * residualTensor.array + (1./6.) * residualTensor.array.swapaxes(0,1)
        Energy = contractTensorSum(CCDEnergyEquation)
        if np.all(abs(residualTensor.array) < 0.00000000000001):
            break
    print(Energy)
    print(doublesTensor.array)

In [69]:
#convergeDoublesAmplitudes(t2Tensor, energyEquation, amplitudeEquation, fockTensor)

In [49]:
from pyscf import cc
trueCCD = cc.CCSD(mf)
old_update_amps = trueCCD.update_amps
def update_amps(t1, t2, eris):
    t1, t2 = old_update_amps(t1, t2, eris)
#    print(t1)
    return (np.zeros_like(t1[0]), np.zeros_like(t1[1])), t2
trueCCD.update_amps = update_amps
trueCCD.diis = False
print(trueCCD.kernel())

(-0.04646969870731496, (array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]]), array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])), (array([[[[-0.        , -0.        , -0.        , -0.        ,
          -0.        , -0.        , -0.        ],
         [-0.        , -0.        , -0.        , -0.        ,
          -0.        , -0.        , -0.        ],
         [-0.        , -0.        , -0.        , -0.        ,
          -0.        , -0.        , -0.        ],
         [-0.        , -0.        , -0.        , -0.        ,
          -0.        , -0.        , -0.        ],
         [-0.        , -0.        , -0.        , -0.        ,
          -0.        , -0.        , -0.        ],
         [-0.        , -0.        , -0.        , -0.        ,
          -0.        , -0.        , -0.        ],
         [-0.        , -0.        , -0.        , -0.        ,
          -0.        , -0.        , -0.        ]],

        [[-0.        , -0.        , 

In [50]:
from pyscf import mp
trueMP2 = mp.MP2(mf)
print(trueMP2.kernel())

(-0.024311010805774455, (array([[[[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           2.16840434e-19],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+00,  2.16840434e-19,
           0.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00, -2.16840434e-19,
           0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
           0.00000000e+00],
         [ 0.00000000e+00, -2.16840434e-19,  0.00000000e+00,
           0.0

In [51]:
print(doublesAmplitudeEquation)

1.0 * v_{p_{1}p_{0}}^{h_{1}h_{0}}
 + -1.0 * v_{p_{0}p_{1}}^{h_{1}h_{0}}
 + 0.5 * f_{h_{2}}^{h_{0}}{t_{2}}_{p_{1}p_{0}}^{h_{2}h_{1}}
 + -0.5 * f_{h_{2}}^{h_{0}}{t_{2}}_{p_{0}p_{1}}^{h_{2}h_{1}}
 + -0.5 * f_{h_{2}}^{h_{1}}{t_{2}}_{p_{1}p_{0}}^{h_{2}h_{0}}
 + 0.5 * f_{h_{2}}^{h_{1}}{t_{2}}_{p_{0}p_{1}}^{h_{2}h_{0}}
 + -0.5 * f_{p_{1}}^{p_{3}}{t_{2}}_{p_{0}p_{3}}^{h_{1}h_{0}}
 + 0.5 * f_{p_{1}}^{p_{3}}{t_{2}}_{p_{3}p_{0}}^{h_{1}h_{0}}
 + 0.5 * f_{p_{0}}^{p_{3}}{t_{2}}_{p_{1}p_{3}}^{h_{1}h_{0}}
 + -0.5 * f_{p_{0}}^{p_{3}}{t_{2}}_{p_{3}p_{1}}^{h_{1}h_{0}}
 + -0.5 * v_{h_{2}h_{3}}^{h_{1}h_{0}}{t_{2}}_{p_{1}p_{0}}^{h_{3}h_{2}}
 + 0.5 * v_{h_{2}h_{3}}^{h_{1}h_{0}}{t_{2}}_{p_{1}p_{0}}^{h_{2}h_{3}}
 + -0.5 * v_{h_{2}p_{1}}^{h_{0}p_{3}}{t_{2}}_{p_{0}p_{3}}^{h_{2}h_{1}}
 + 0.5 * v_{h_{2}p_{1}}^{h_{0}p_{3}}{t_{2}}_{p_{3}p_{0}}^{h_{2}h_{1}}
 + 0.5 * v_{h_{2}p_{0}}^{h_{0}p_{3}}{t_{2}}_{p_{1}p_{3}}^{h_{2}h_{1}}
 + -0.5 * v_{h_{2}p_{0}}^{h_{0}p_{3}}{t_{2}}_{p_{3}p_{1}}^{h_{2}h_{1}}
 + 0.5 * v_{h_{2}p_{1

In [52]:
convergeDoublesAmplitudes(t2Tensor, energyEquation, doublesAmplitudeEquation, fockTensor)

[[[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

  [[ 0.00000000e+00  3.30086167e-03  0.00000000e+00  6.59818153e-03]
   [-3.30086167e-03  0.00000000e+00 -6.59818153e-03  0.00000000e+00]
   [ 0.00000000e+00  6.59818153e-03  0.00000000e+00  6.30349976e-02]
   [-6.59818153e-03  0.00000000e+00 -6.30349976e-02  0.00000000e+00]]

  [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]]

  ...

  [[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
   [ 0.00000000e+00  

In [53]:
bohr = 0.529177249

H2sep = 1.605 * bohr

mol = gto.Mole()
mol.verbose = 1
mol.atom = 'Li 0 0 0'
mol.basis = 'sto-3g'
#mol.atom = 'H 0 0 0; H 0 0 ' + str(H2sep)
#mol.basis = '6-31g'
mol.spin = 1
mol.build()

In [54]:
mf = scf.ROHF(mol)
mf.kernel()

-7.31552598128109

In [55]:
mol.nao

5

In [56]:
mol.nelec

(2, 1)

In [57]:
mf.mo_coeff.T.dot(mf.get_fock()).dot(mf.mo_coeff)

array([[-2.35349064e+00, -8.15538341e-09,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [-8.15538343e-09, -3.89597612e-02,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.60521286e-01,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.60521286e-01,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.60521286e-01]])

In [74]:
cisolver = fci.FCI(mol, mf.mo_coeff)

Norbs = mol.nao
Nocc = mf.nelec
vacuum = [1] * Nocc[0] + [0] * (Norbs - Nocc[0])

h1 = mf.mo_coeff.T.dot(mf.get_hcore()).dot(mf.mo_coeff)
eri = ao2mo.kernel(mol, mf.mo_coeff, compact=False)

h2Tensor.array = eri.reshape((Norbs, Norbs, Norbs, Norbs)).swapaxes(2,3).swapaxes(1,2)

fock = h1
for p in range(Norbs):
    for q in range(Norbs):
        fock[p,q] += sum([2 * h2Tensor.array[p,i,q,i] - h2Tensor.array[p,i,i,q] for i in range(Nocc[0])])
fockTensor.array = fock

fockTensor.assignDiagramArrays(vacuum)
h2Tensor.assignDiagramArrays(vacuum)
t2Tensor.getShape(vacuum)

In [75]:
Norbs

5

In [76]:
mf.get_fock()

NPArrayWithTag([[-2.3509493 , -0.64129033,  0.        ,  0.        ,
                  0.        ],
                [-0.64129033, -0.21166477,  0.        ,  0.        ,
                  0.        ],
                [ 0.        ,  0.        ,  0.16052129,  0.        ,
                  0.        ],
                [ 0.        ,  0.        ,  0.        ,  0.16052129,
                  0.        ],
                [ 0.        ,  0.        ,  0.        ,  0.        ,
                  0.16052129]])

In [77]:
fock

array([[-1.96860161e+00, -8.15538403e-09,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [-8.15538403e-09,  1.02252664e-01,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  4.15796450e-01,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         4.15796450e-01,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  4.15796450e-01]])

In [78]:
mf.mo_coeff.T.dot(mf.get_fock()).dot(mf.mo_coeff)

array([[-2.35349064e+00, -8.15538341e-09,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [-8.15538343e-09, -3.89597612e-02,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.60521286e-01,
         0.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.60521286e-01,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  1.60521286e-01]])

In [79]:
fockTensor.array = mf.mo_coeff.T.dot(mf.get_fock()).dot(mf.mo_coeff)


In [80]:
vacuumSpinOrb = [1, 1] * Nocc[1] + [1, 0] * (Nocc[0] - Nocc[1]) + [0, 0] * (Norbs - Nocc[0])

In [81]:
vacuumSpinOrb

[1, 1, 1, 0, 0, 0, 0, 0, 0, 0]

In [82]:
orb2spinorb(fockTensor)
orb2spinorb(h2Tensor)

(5, 5)
(10, 10)
(0, 0) (0, 0)
()
2
(0, 0)
(0,)
2
(1, 1)
(0, 1) (0, 2)
()
2
(0, 2)
(0,)
2
(1, 3)
(0, 2) (0, 4)
()
2
(0, 4)
(0,)
2
(1, 5)
(0, 3) (0, 6)
()
2
(0, 6)
(0,)
2
(1, 7)
(0, 4) (0, 8)
()
2
(0, 8)
(0,)
2
(1, 9)
(1, 0) (2, 0)
()
2
(2, 0)
(0,)
2
(3, 1)
(1, 1) (2, 2)
()
2
(2, 2)
(0,)
2
(3, 3)
(1, 2) (2, 4)
()
2
(2, 4)
(0,)
2
(3, 5)
(1, 3) (2, 6)
()
2
(2, 6)
(0,)
2
(3, 7)
(1, 4) (2, 8)
()
2
(2, 8)
(0,)
2
(3, 9)
(2, 0) (4, 0)
()
2
(4, 0)
(0,)
2
(5, 1)
(2, 1) (4, 2)
()
2
(4, 2)
(0,)
2
(5, 3)
(2, 2) (4, 4)
()
2
(4, 4)
(0,)
2
(5, 5)
(2, 3) (4, 6)
()
2
(4, 6)
(0,)
2
(5, 7)
(2, 4) (4, 8)
()
2
(4, 8)
(0,)
2
(5, 9)
(3, 0) (6, 0)
()
2
(6, 0)
(0,)
2
(7, 1)
(3, 1) (6, 2)
()
2
(6, 2)
(0,)
2
(7, 3)
(3, 2) (6, 4)
()
2
(6, 4)
(0,)
2
(7, 5)
(3, 3) (6, 6)
()
2
(6, 6)
(0,)
2
(7, 7)
(3, 4) (6, 8)
()
2
(6, 8)
(0,)
2
(7, 9)
(4, 0) (8, 0)
()
2
(8, 0)
(0,)
2
(9, 1)
(4, 1) (8, 2)
()
2
(8, 2)
(0,)
2
(9, 3)
(4, 2) (8, 4)
()
2
(8, 4)
(0,)
2
(9, 5)
(4, 3) (8, 6)
()
2
(8, 6)
(0,)
2
(9, 7)
(4, 4) (8, 8)
()
2
(8, 8

In [103]:
fockTensor.assignDiagramArrays(vacuumSpinOrb)
h2Tensor.assignDiagramArrays(vacuumSpinOrb)
t1Tensor.getShape(vacuumSpinOrb)
t2Tensor.getShape(vacuumSpinOrb)

In [104]:
fockTensor.array.shape

(10, 10)

In [105]:
t2Tensor.array.shape

(7, 7, 3, 3)

In [106]:
t2Tensor.array

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


  

In [107]:
residualTensor = Tensor("R", ['p', 'p'], ['h', 'h'])
residualTensor.array = contractTensorSum(doublesAmplitudeEquation)

In [108]:
residualTensor.array

array([[[[ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ]],

        [[ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ]],

        [[ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ]],

        [[ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ]],

        [[ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ]],

        [[ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ]],

        [[ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0

In [110]:
def iterateDoublesAmplitudes(doublesTensor, residual, fockMatrix, spinFree=True):
    amplitudes = doublesTensor.array
    for i in range(amplitudes.shape[0]):
        for j in range(amplitudes.shape[1]):
            for k in range(amplitudes.shape[2]):
                for l in range(amplitudes.shape[3]):
                    if (fockMatrix[i + amplitudes.shape[2], i + amplitudes.shape[2]] + fockMatrix[j + amplitudes.shape[3], j + amplitudes.shape[3]] - fockMatrix[k, k] - fockMatrix[l, l]) == 0:
                        print("div 0 error")
                        print(i, j, k, l, residual.array[i,j,k,l])
                        amplitudes[i,j,k,l] -= 0
                    else:
                        amplitudes[i,j,k,l] -= residual.array[i,j,k,l] / (fockMatrix[i + amplitudes.shape[2], i + amplitudes.shape[2]] + fockMatrix[j + amplitudes.shape[3], j + amplitudes.shape[3]] - fockMatrix[k, k] - fockMatrix[l, l])
#    if spinFree:
#        amplitudes = (1./3.) * amplitudes + (1./6.) * amplitudes.swapaxes(0,1)
    return amplitudes

In [111]:
iterateDoublesAmplitudes(t2Tensor, residualTensor, fockTensor.array)

div 0 error
0 0 2 2 0.0


array([[[[ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ]],

        [[ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ]],

        [[ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ]],

        [[ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ]],

        [[ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ]],

        [[ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ]],

        [[ 0.        ,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0

In [86]:
trueMP2 = mp.MP2(mf)
print(trueMP2.kernel())

(-0.0002649961677917838, (array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]]), array([[[[-0.        , -0.00195551, -0.        , -0.        ],
         [-0.        , -0.        , -0.00195551, -0.        ],
         [-0.        , -0.        , -0.        , -0.00195551]]],


       [[[-0.        , -0.00504649, -0.        , -0.        ],
         [-0.        , -0.        , -0.00504649, -0.        ],
         [-0.        , -0.        , -0.        , -0.00504649]]]]), array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])))


In [113]:
trueMP2.kernel()[1][1]

array([[[[-0.        , -0.00195551, -0.        , -0.        ],
         [-0.        , -0.        , -0.00195551, -0.        ],
         [-0.        , -0.        , -0.        , -0.00195551]]],


       [[[-0.        , -0.00504649, -0.        , -0.        ],
         [-0.        , -0.        , -0.00504649, -0.        ],
         [-0.        , -0.        , -0.        , -0.00504649]]]])

In [87]:
trueCCD = cc.CCSD(mf)
old_update_amps = trueCCD.update_amps
def update_amps(t1, t2, eris):
    t1, t2 = old_update_amps(t1, t2, eris)
#    print(t1)
    return (np.zeros_like(t1[0]), np.zeros_like(t1[1])), t2
trueCCD.update_amps = update_amps
trueCCD.diis = False
print(trueCCD.kernel())

(-0.00030987449141026385, (array([[0., 0., 0.],
       [0., 0., 0.]]), array([[0., 0., 0., 0.]])), (array([[[[-0., -0., -0.],
         [-0., -0., -0.],
         [-0., -0., -0.]],

        [[-0., -0., -0.],
         [-0., -0., -0.],
         [-0., -0., -0.]]],


       [[[-0., -0., -0.],
         [-0., -0., -0.],
         [-0., -0., -0.]],

        [[-0., -0., -0.],
         [-0., -0., -0.],
         [-0., -0., -0.]]]]), array([[[[-0.        , -0.00198622, -0.        , -0.        ],
         [-0.        , -0.        , -0.00198622, -0.        ],
         [-0.        , -0.        , -0.        , -0.00198622]]],


       [[[-0.        , -0.00611688, -0.        , -0.        ],
         [-0.        , -0.        , -0.00611688, -0.        ],
         [-0.        , -0.        , -0.        , -0.00611688]]]]), array([[[[-0., -0., -0., -0.],
         [-0., -0., -0., -0.],
         [-0., -0., -0., -0.],
         [-0., -0., -0., -0.]]]])))


In [114]:
def convergeDoublesAmplitudes(doublesTensor, CCDEnergyEquation, CCDAmplitudeEquation, fockTensor, spinFree=True):
    residualTensor = Tensor("R", ['p', 'p'], ['h', 'h'])
    doublesTensor.array = np.zeros_like(doublesTensor.array)
    Energy = contractTensorSum(CCDEnergyEquation)
    residualTensor.array = contractTensorSum(CCDAmplitudeEquation)
#    residualTensor.array = (1./3.) * residualTensor.array + (1./6.) * residualTensor.array.swapaxes(0,1)
    print(residualTensor.array)
    while True:
        print(Energy)
        doublesTensor.array = iterateDoublesAmplitudes(doublesTensor, residualTensor, fockTensor.array, spinFree)
        residualTensor.array = contractTensorSum(CCDAmplitudeEquation)
#        residualTensor.array = (1./3.) * residualTensor.array + (1./6.) * residualTensor.array.swapaxes(0,1)
        Energy = contractTensorSum(CCDEnergyEquation)
        if np.all(abs(residualTensor.array) < 0.00000000000001):
            break
    print(Energy)
    print(doublesTensor.array)

In [115]:
convergeDoublesAmplitudes(t2Tensor, energyEquation, doublesAmplitudeEquation, fockTensor)

[[[[ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]]

  [[ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]]

  [[ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]]

  [[ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]]

  [[ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]]

  [[ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]]

  [[ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]]]


 [[[ 0.          0.          0.        ]
   [ 0.          0.          0.        ]
   [ 0.          0.          0.        ]]